"""Add params column to form table

Revision ID: 4dd5b86a2349
Revises: fb7f8e463f99
Create Date: 2025-12-04 14:54:49.844607

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd5b86a2349"
down_revision: Union[str, Sequence[str], None] = "fb7f8e463f99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("name", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("original_file", sa.JSON(), nullable=True))
    op.add_column("documents", sa.Column("processing_file", sa.JSON(), nullable=True))
    op.add_column("documents", sa.Column("params", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_documents_document_number"), table_name="documents")
    op.drop_column("documents", "document_number")
    op.drop_column("documents", "data")
    op.add_column("files", sa.Column("template_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_files_name"), table_name="files")
    op.create_index(op.f("ix_files_template_id"), "files", ["template_id"], unique=False)
    op.create_foreign_key(None, "files", "templates", ["template_id"], ["id"], ondelete="CASCADE")
    op.drop_column("files", "description")
    op.add_column("forms", sa.Column("params", sa.JSON(), nullable=True))
    op.add_column("ocr_jobs", sa.Column("job_id", sa.String(length=255), nullable=False))
    op.add_column("ocr_jobs", sa.Column("image_path", sa.Text(), nullable=True))
    op.add_column("ocr_jobs", sa.Column("result_text", sa.Text(), nullable=True))
    op.add_column("ocr_jobs", sa.Column("error_message", sa.Text(), nullable=True))
    # Create the jobstatus enum type
    op.execute("CREATE TYPE jobstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    # Convert the status column to use the enum type
    op.execute("ALTER TABLE ocr_jobs ALTER COLUMN status TYPE jobstatus USING status::jobstatus")
    op.drop_index(op.f("ix_ocr_jobs_status"), table_name="ocr_jobs")
    op.create_index(op.f("ix_ocr_jobs_job_id"), "ocr_jobs", ["job_id"], unique=True)
    op.drop_column("ocr_jobs", "error")
    op.drop_column("ocr_jobs", "tesseract_params")
    op.drop_column("ocr_jobs", "result")
    op.drop_column("ocr_jobs", "image_data")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_column("templates", "tesseract_params")
    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    op.add_column(
        "templates",
        sa.Column("tesseract_params", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.add_column("ocr_jobs", sa.Column("image_data", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "ocr_jobs", sa.Column("result", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.add_column(
        "ocr_jobs",
        sa.Column("tesseract_params", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column("ocr_jobs", sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_ocr_jobs_job_id"), table_name="ocr_jobs")
    op.create_index(op.f("ix_ocr_jobs_status"), "ocr_jobs", ["status"], unique=False)
    # Convert the status column back to VARCHAR
    op.alter_column(
        "ocr_jobs",
        "status",
        existing_type=sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="jobstatus"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # Drop the jobstatus enum type
    op.execute("DROP TYPE IF EXISTS jobstatus")
    op.drop_column("ocr_jobs", "error_message")
    op.drop_column("ocr_jobs", "result_text")
    op.drop_column("ocr_jobs", "image_path")
    op.drop_column("ocr_jobs", "job_id")
    op.drop_column("forms", "params")
    op.add_column("files", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "files", type_="foreignkey")
    op.drop_index(op.f("ix_files_template_id"), table_name="files")
    op.create_index(op.f("ix_files_name"), "files", ["name"], unique=False)
    op.drop_column("files", "template_id")
    op.add_column(
        "documents", sa.Column("data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.add_column("documents", sa.Column("document_number", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f("ix_documents_document_number"), "documents", ["document_number"], unique=False)
    op.drop_column("documents", "params")
    op.drop_column("documents", "processing_file")
    op.drop_column("documents", "original_file")
    op.drop_column("documents", "name")
    # ### end Alembic commands ###
